name: Docker Build and Push

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set Docker tag
      id: set-tag
      run: |
        if [ "${{ github.ref }}" = "refs/heads/devn" ]; then
          echo "TAG=latest" >> $GITHUB_OUTPUT
        else
          echo "TAG=dev" >> $GITHUB_OUTPUT
        fi
    
    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/infrastructure/Dockerfile
        push: true
        tags: apurvagargote/portfolio-frontend:${{ steps.set-tag.outputs.TAG }}
    
    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        file: ./backend/Dockerfile
        push: true
        tags: apurvagargote/portfolio-backend:${{ steps.set-tag.outputs.TAG }}